version: '2'
services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    privileged: true
    volumes:
      - /data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/conf.d:/etc/nginx/conf.d
      - /data/nginx/html:/usr/share/nginx/html
      - /data/nginx/logs:/var/log/nginx
  docker:
    restart: always
    image: gin-blog:v1
    volumes:
      - /data/server/gin-blog/runtime/logs:/go/src/gin-blog/runtime/logs
    expose:
      - "8000"
    depends_on:
      - nginx
